version: '3.4'

services:
  node-app:
    container_name: node-app
    build:
      context: .
      target: dependencies
      dockerfile: Dockerfile
    image: node-app:dev
    command: npm run debug
    volumes:
      - ./:/opt/node_app
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - /opt/node_app/node_modules

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
