version: '3.4'

services:
  node-app:
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_NAME=task1
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 3000:3000

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task1
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
